version: 2

project_name: hop

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/hop
    ldflags:
      - -s -w
      - -X github.com/danmartuszewski/hop/internal/cmd.Version={{.Version}}
      - -X github.com/danmartuszewski/hop/internal/cmd.Commit={{.Commit}}
      - -X github.com/danmartuszewski/hop/internal/cmd.BuildDate={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

homebrew_casks:
  - name: hop
    binaries:
      - hop
    repository:
      owner: danmartuszewski
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/danmartuszewski/hop
    description: "Fast, elegant SSH connection manager"
